# Generated by Django 3.1.2 on 2020-11-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('txt', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
