# Generated by Django 3.1.2 on 2020-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='txten',
            field=models.TextField(default=0.0, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ak',
            name='typesen',
            field=models.CharField(default=0.0, max_length=250, verbose_name='Title'),
        ),
    ]
