# Generated by Django 3.1.2 on 2020-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201107_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='sk',
            field=models.CharField(default='', max_length=250, verbose_name='Промо код'),
        ),
        migrations.AddField(
            model_name='ak',
            name='sken',
            field=models.CharField(default='', max_length=250, verbose_name='Promo code'),
        ),
        migrations.AlterField(
            model_name='ak',
            name='txten',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='ak',
            name='typesen',
            field=models.CharField(default='', max_length=250, verbose_name='Title'),
        ),
    ]
